name: Tests unitaires

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compilation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/bin/**
            **/obj/**

  test_add:
    needs: compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test Addition
        run: dotnet test --filter "FullyQualifiedName~Addition"

  test_sub:
    needs: compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test Soustraction
        run: dotnet test --filter "FullyQualifiedName~Subtraction"

  test_mul:
    needs: compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test Multiplication
        run: dotnet test --filter "FullyQualifiedName~Multiplication"

  test_div:
    needs: compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test Division
        run: dotnet test --filter "FullyQualifiedName~Division"

  test_car:
    needs: compilation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Test Racine Carrée
        run: dotnet test --filter "FullyQualifiedName~Sqrt"

  deploy:
    needs: [test_add, test_sub, test_mul, test_div, test_car]
    if: success()
    runs-on: windows-latest
    steps:
      - name: Deploy
        run: echo "Déploiement réussi ! Tous les tests sont passés"